name: Update ETH Price Log

on:
  schedule:
    - cron: '*/2 * * * *'  # Каждые 2 минуты
  workflow_dispatch:

jobs:
  update-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install pandas requests python-binance
      
      - name: Update price log
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        run: |
          python -c "
          import pandas as pd
          from datetime import datetime
          # [Код для однократного логирования]
          "
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add prices_log.csv
          git commit -m "Auto-update ETH price log [skip ci]"
          git push
